version: 0.0
os: linux
files:
  - source: bin/students
    destination: /var/www/backend/bin
  - source: config
    destination: /var/www/backend/config
 - source: deploy-scripts
    destination: /var/www/backend/deploy-scripts
hooks:
  AfterInstall:
    - location: /var/www/backend/deploy-scripts/after-install.sh
  ApplicationStart:
    - location: /var/www/backend/deploy-scripts/start-app.sh
