version: 0.2

env:
  secrets-manager:
    DB_SECRET: prod/backend/db
    JWT_SECRET: prod/backend/secretkey

phases:
  install:
    commands:
      - "apt-get install -y jq"
  pre_build:
    commands:
      - "echo 'Cleaning up previous build artifacts...'"
      - "rm -rf bin config"
      - "echo 'Retrieving DB secrets...'"
      - "mkdir -p config"
      - |
        echo $DB_SECRET | jq -r '{
          host: .host,
          port: .port,
          username: .username,
          password: .password,
          database: .database
        }' > config/postgrescreds.prod.yml
      - "echo 'Retrieving JWT secret...'"
      - "if [ $? -eq 0 ]; then echo 'Credentials file created successfully'; else echo 'Failed to create credentials file'; fi"
      - |
        echo $JWT_SECRET | jq -r '{
          secretKey: .secretKey
        }' > config/secrets.yml
  build:
    commands:
      - "echo 'Running your build commands...'"
      - "mkdir -p bin"
      - "GOOS=linux GOARCH=amd64 go build -ldflags '-w -s' -o bin/students"
      - "echo 'web: bin/students' > Procfile"
  post_build:
    commands:
      - "echo 'Packaging up build artifacts...'"
      
artifacts:
  files:
  - bin/students
  - config/**/*
  - Procfile
  - appspec.yml